# Generated by Django 3.1 on 2022-04-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_profile_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
